[workspace]
default-members = ["server"]
members = [
    "auth",
    "config",
    "db",
    "graphql",
    "mailers",
    "scripts",
    "scrapers",
    "server",
    "geocodio",
    "votesmart",
    "legiscan",
    "open-secrets",
]
