[package]
name = "cli"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
db = { path = "../db" }
legiscan = { path = "../legiscan" }
votesmart = { path = "../votesmart" }
dotenv = "0.15.0"
structopt = "0.3.25"
serde_json = "1.0.71"
tokio = { version = "1.8", features = ["full"] }
sqlx = { version = "0.5.9", features = ["postgres"] }
slugify = "0.1.0"
colored = "2.0.0"
csv = "1.1"
uuid = "0.8.2"
chrono = { version = "0.4.19", features = ["serde"] }
anyhow = "1.0.45"
strum = "0.23.0"
strum_macros = "0.23.0"
serde_yaml = "0.8.23"
